services:
  app:
    platform: linux/arm64
    build: .
    image: my-python-dev-env
    volumes:
      - ./srv/HW_CI_test:/srv/HW_CI_test
    ports:
      - "7877:8777"
    command: uvicorn src.main:app --host 0.0.0.0 --port 8777 --reload
    environment:
      - PYTHONPATH=/srv/HW_CI_test/src  # Add PYTHONPATH
    container_name: HW_CI_test

