version: '3.8'

services:
  HW_CI_test:
    image: my-python-dev-env
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/srv/HW_CI_test/src
      - ./tests:/srv/HW_CI_test/tests
    ports:
      - "5000:5000"  # Change to your required port mapping
